a=int(input("enter a number:"))
b=int(input("enter a number:"))
c=int(input("enter a number:"))
print("addition:",a+b+c)
print("subtraction:",a-b-c)
print("multiplication:",a*b*c)
print("modulous:",a%b)
print("power:",a**b)
